# Generated by Django 4.1.7 on 2023-04-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_productos_created_productos_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='disponibilidad',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.FloatField(),
        ),
    ]
